language: node_js
node_js:
  - "10"
branches:
  only:
    - master
    - gh-pages
install:
  - yarn global add lerna jest
  - yarn
  - lerna bootstrap
script:
  - yarn test
  - yarn build
  - yarn build-site
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: app/dist
  on:
    branch: master
